### PR TITLE
Muse markup

### PR DESCRIPTION
**Pull request by melmothx**
See documentations for details.

Thanks in advance

### CODE REVIEW

**Comment by jmcnamara** [comment]
Hi,

Thanks for that. 

Can you squash/rebase the changes into a single commit and resubmit (using --force if necessary).

John

**Comment by melmothx** [comment]
Done

**Comment by jmcnamara** [comment]
Merged. Thanks.

Give we a day or two to get it to CPAN.

**Comment by melmothx** [comment]
Thanks to you for the amazingly quick action.

This close https://github.com/melmothx/amusewiki/issues/4

**Pull request merged**
